// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api.proto

/*
Package client is a generated protocol buffer package.

It is generated from these files:
	proto/api.proto

It has these top-level messages:
	BlockData
	Block
	FileMeta
	Directory
	Volume
	HostStash
	OpenRequest
	GetBlockRequest
	AppendToBlockRequest
	DeleteBlockRequest
	CreateBlockRequest
	GetFileRequest
	GetVolumeRequest
	GetDirectoryRequest
	Node
	BlockStashSuggestion
	WriteResult
	NewDirectoryContract
	AcquireFileWriteLockContract
	ReleaseFileWriteLockContract
	TouchFileContract
	ConfirmBlockContract
	ConfirmBlockCreationContract
	FileWriteLock
	DirectoryItem
	ListDirectoryResponse
	ListDirectoryRequest
	Nothing
*/
package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DirectoryItem_ItemType int32

const (
	DirectoryItem_FILE DirectoryItem_ItemType = 0
	DirectoryItem_DIR  DirectoryItem_ItemType = 1
)

var DirectoryItem_ItemType_name = map[int32]string{
	0: "FILE",
	1: "DIR",
}
var DirectoryItem_ItemType_value = map[string]int32{
	"FILE": 0,
	"DIR":  1,
}

func (x DirectoryItem_ItemType) String() string {
	return proto.EnumName(DirectoryItem_ItemType_name, int32(x))
}
func (DirectoryItem_ItemType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{24, 0} }

type BlockData struct {
	Group uint64 `protobuf:"varint,1,opt,name=group" json:"group,omitempty"`
	Index uint64 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Size  uint32 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	File  []byte `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Data  []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *BlockData) Reset()                    { *m = BlockData{} }
func (m *BlockData) String() string            { return proto.CompactTextString(m) }
func (*BlockData) ProtoMessage()               {}
func (*BlockData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BlockData) GetGroup() uint64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *BlockData) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BlockData) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *BlockData) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *BlockData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Block struct {
	Hosts []uint64 `protobuf:"varint,2,rep,packed,name=hosts" json:"hosts,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Block) GetHosts() []uint64 {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type FileMeta struct {
	Name         string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Size         uint64   `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	LastModified uint64   `protobuf:"varint,3,opt,name=last_modified,json=lastModified" json:"last_modified,omitempty"`
	CreatedAt    uint64   `protobuf:"varint,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	BlockSize    uint32   `protobuf:"varint,6,opt,name=block_size,json=blockSize" json:"block_size,omitempty"`
	Key          []byte   `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty"`
	Blocks       []*Block `protobuf:"bytes,8,rep,name=blocks" json:"blocks,omitempty"`
}

func (m *FileMeta) Reset()                    { *m = FileMeta{} }
func (m *FileMeta) String() string            { return proto.CompactTextString(m) }
func (*FileMeta) ProtoMessage()               {}
func (*FileMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FileMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileMeta) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileMeta) GetLastModified() uint64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

func (m *FileMeta) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *FileMeta) GetBlockSize() uint32 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *FileMeta) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *FileMeta) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type Directory struct {
	Name  string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Key   []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Files [][]byte `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
}

func (m *Directory) Reset()                    { *m = Directory{} }
func (m *Directory) String() string            { return proto.CompactTextString(m) }
func (*Directory) ProtoMessage()               {}
func (*Directory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Directory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Directory) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Directory) GetFiles() [][]byte {
	if m != nil {
		return m.Files
	}
	return nil
}

type Volume struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Key          []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Replications uint32 `protobuf:"varint,3,opt,name=replications" json:"replications,omitempty"`
	BlockSize    uint32 `protobuf:"varint,4,opt,name=block_size,json=blockSize" json:"block_size,omitempty"`
	RootDir      []byte `protobuf:"bytes,5,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
}

func (m *Volume) Reset()                    { *m = Volume{} }
func (m *Volume) String() string            { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()               {}
func (*Volume) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Volume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Volume) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Volume) GetReplications() uint32 {
	if m != nil {
		return m.Replications
	}
	return 0
}

func (m *Volume) GetBlockSize() uint32 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *Volume) GetRootDir() []byte {
	if m != nil {
		return m.RootDir
	}
	return nil
}

type HostStash struct {
	HostId   uint64 `protobuf:"varint,1,opt,name=host_id,json=hostId" json:"host_id,omitempty"`
	Capacity uint64 `protobuf:"varint,2,opt,name=capacity" json:"capacity,omitempty"`
	Used     uint64 `protobuf:"varint,3,opt,name=used" json:"used,omitempty"`
	Owner    uint64 `protobuf:"varint,4,opt,name=owner" json:"owner,omitempty"`
}

func (m *HostStash) Reset()                    { *m = HostStash{} }
func (m *HostStash) String() string            { return proto.CompactTextString(m) }
func (*HostStash) ProtoMessage()               {}
func (*HostStash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HostStash) GetHostId() uint64 {
	if m != nil {
		return m.HostId
	}
	return 0
}

func (m *HostStash) GetCapacity() uint64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *HostStash) GetUsed() uint64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *HostStash) GetOwner() uint64 {
	if m != nil {
		return m.Owner
	}
	return 0
}

type OpenRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Key  []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *OpenRequest) Reset()                    { *m = OpenRequest{} }
func (m *OpenRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenRequest) ProtoMessage()               {}
func (*OpenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *OpenRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OpenRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetBlockRequest struct {
	Group uint64 `protobuf:"varint,1,opt,name=group" json:"group,omitempty"`
	Index uint64 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	File  []byte `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
}

func (m *GetBlockRequest) Reset()                    { *m = GetBlockRequest{} }
func (m *GetBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlockRequest) ProtoMessage()               {}
func (*GetBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetBlockRequest) GetGroup() uint64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *GetBlockRequest) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *GetBlockRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type AppendToBlockRequest struct {
	Group  uint64 `protobuf:"varint,1,opt,name=group" json:"group,omitempty"`
	Index  uint64 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Offset uint32 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	File   []byte `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Data   []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *AppendToBlockRequest) Reset()                    { *m = AppendToBlockRequest{} }
func (m *AppendToBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*AppendToBlockRequest) ProtoMessage()               {}
func (*AppendToBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AppendToBlockRequest) GetGroup() uint64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *AppendToBlockRequest) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *AppendToBlockRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *AppendToBlockRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *AppendToBlockRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteBlockRequest struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *DeleteBlockRequest) Reset()                    { *m = DeleteBlockRequest{} }
func (m *DeleteBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteBlockRequest) ProtoMessage()               {}
func (*DeleteBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteBlockRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type CreateBlockRequest struct {
	Group     uint64 `protobuf:"varint,1,opt,name=group" json:"group,omitempty"`
	Index     uint64 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	File      []byte `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *CreateBlockRequest) Reset()                    { *m = CreateBlockRequest{} }
func (m *CreateBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateBlockRequest) ProtoMessage()               {}
func (*CreateBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CreateBlockRequest) GetGroup() uint64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *CreateBlockRequest) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *CreateBlockRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *CreateBlockRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetFileRequest struct {
	Group uint64 `protobuf:"varint,1,opt,name=group" json:"group,omitempty"`
	File  []byte `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
}

func (m *GetFileRequest) Reset()                    { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()               {}
func (*GetFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetFileRequest) GetGroup() uint64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *GetFileRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type GetVolumeRequest struct {
	Group uint64 `protobuf:"varint,1,opt,name=group" json:"group,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *GetVolumeRequest) Reset()                    { *m = GetVolumeRequest{} }
func (m *GetVolumeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetVolumeRequest) ProtoMessage()               {}
func (*GetVolumeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetVolumeRequest) GetGroup() uint64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *GetVolumeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetDirectoryRequest struct {
	Group uint64 `protobuf:"varint,1,opt,name=group" json:"group,omitempty"`
	Key   []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *GetDirectoryRequest) Reset()                    { *m = GetDirectoryRequest{} }
func (m *GetDirectoryRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDirectoryRequest) ProtoMessage()               {}
func (*GetDirectoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetDirectoryRequest) GetGroup() uint64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *GetDirectoryRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type Node struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	NodeId  uint64 `protobuf:"varint,2,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	Remains uint64 `protobuf:"varint,3,opt,name=remains" json:"remains,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Node) GetNodeId() uint64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *Node) GetRemains() uint64 {
	if m != nil {
		return m.Remains
	}
	return 0
}

type BlockStashSuggestion struct {
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *BlockStashSuggestion) Reset()                    { *m = BlockStashSuggestion{} }
func (m *BlockStashSuggestion) String() string            { return proto.CompactTextString(m) }
func (*BlockStashSuggestion) ProtoMessage()               {}
func (*BlockStashSuggestion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *BlockStashSuggestion) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type WriteResult struct {
	Succeed bool   `protobuf:"varint,1,opt,name=succeed" json:"succeed,omitempty"`
	Remains uint64 `protobuf:"varint,2,opt,name=remains" json:"remains,omitempty"`
	Key     []byte `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *WriteResult) Reset()                    { *m = WriteResult{} }
func (m *WriteResult) String() string            { return proto.CompactTextString(m) }
func (*WriteResult) ProtoMessage()               {}
func (*WriteResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *WriteResult) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

func (m *WriteResult) GetRemains() uint64 {
	if m != nil {
		return m.Remains
	}
	return 0
}

func (m *WriteResult) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type NewDirectoryContract struct {
	ParentDir []byte     `protobuf:"bytes,1,opt,name=parent_dir,json=parentDir,proto3" json:"parent_dir,omitempty"`
	Dir       *Directory `protobuf:"bytes,3,opt,name=dir" json:"dir,omitempty"`
}

func (m *NewDirectoryContract) Reset()                    { *m = NewDirectoryContract{} }
func (m *NewDirectoryContract) String() string            { return proto.CompactTextString(m) }
func (*NewDirectoryContract) ProtoMessage()               {}
func (*NewDirectoryContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *NewDirectoryContract) GetParentDir() []byte {
	if m != nil {
		return m.ParentDir
	}
	return nil
}

func (m *NewDirectoryContract) GetDir() *Directory {
	if m != nil {
		return m.Dir
	}
	return nil
}

type AcquireFileWriteLockContract struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *AcquireFileWriteLockContract) Reset()                    { *m = AcquireFileWriteLockContract{} }
func (m *AcquireFileWriteLockContract) String() string            { return proto.CompactTextString(m) }
func (*AcquireFileWriteLockContract) ProtoMessage()               {}
func (*AcquireFileWriteLockContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *AcquireFileWriteLockContract) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type ReleaseFileWriteLockContract struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *ReleaseFileWriteLockContract) Reset()                    { *m = ReleaseFileWriteLockContract{} }
func (m *ReleaseFileWriteLockContract) String() string            { return proto.CompactTextString(m) }
func (*ReleaseFileWriteLockContract) ProtoMessage()               {}
func (*ReleaseFileWriteLockContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ReleaseFileWriteLockContract) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type TouchFileContract struct {
	ClientTime uint64 `protobuf:"varint,1,opt,name=client_time,json=clientTime" json:"client_time,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Dir        []byte `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`
	Volume     []byte `protobuf:"bytes,4,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (m *TouchFileContract) Reset()                    { *m = TouchFileContract{} }
func (m *TouchFileContract) String() string            { return proto.CompactTextString(m) }
func (*TouchFileContract) ProtoMessage()               {}
func (*TouchFileContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *TouchFileContract) GetClientTime() uint64 {
	if m != nil {
		return m.ClientTime
	}
	return 0
}

func (m *TouchFileContract) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TouchFileContract) GetDir() []byte {
	if m != nil {
		return m.Dir
	}
	return nil
}

func (m *TouchFileContract) GetVolume() []byte {
	if m != nil {
		return m.Volume
	}
	return nil
}

type ConfirmBlockContract struct {
	NodeId uint64              `protobuf:"varint,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	Index  uint64              `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	File   []byte              `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Req    *CreateBlockRequest `protobuf:"bytes,4,opt,name=req" json:"req,omitempty"`
}

func (m *ConfirmBlockContract) Reset()                    { *m = ConfirmBlockContract{} }
func (m *ConfirmBlockContract) String() string            { return proto.CompactTextString(m) }
func (*ConfirmBlockContract) ProtoMessage()               {}
func (*ConfirmBlockContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ConfirmBlockContract) GetNodeId() uint64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *ConfirmBlockContract) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ConfirmBlockContract) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *ConfirmBlockContract) GetReq() *CreateBlockRequest {
	if m != nil {
		return m.Req
	}
	return nil
}

type ConfirmBlockCreationContract struct {
	Index      uint64   `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	ClientTime uint64   `protobuf:"varint,2,opt,name=client_time,json=clientTime" json:"client_time,omitempty"`
	NodeIds    []uint64 `protobuf:"varint,3,rep,packed,name=node_ids,json=nodeIds" json:"node_ids,omitempty"`
	File       []byte   `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
}

func (m *ConfirmBlockCreationContract) Reset()                    { *m = ConfirmBlockCreationContract{} }
func (m *ConfirmBlockCreationContract) String() string            { return proto.CompactTextString(m) }
func (*ConfirmBlockCreationContract) ProtoMessage()               {}
func (*ConfirmBlockCreationContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ConfirmBlockCreationContract) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ConfirmBlockCreationContract) GetClientTime() uint64 {
	if m != nil {
		return m.ClientTime
	}
	return 0
}

func (m *ConfirmBlockCreationContract) GetNodeIds() []uint64 {
	if m != nil {
		return m.NodeIds
	}
	return nil
}

func (m *ConfirmBlockCreationContract) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type FileWriteLock struct {
	Group uint64 `protobuf:"varint,1,opt,name=group" json:"group,omitempty"`
	Owner uint64 `protobuf:"varint,2,opt,name=owner" json:"owner,omitempty"`
	Key   []byte `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *FileWriteLock) Reset()                    { *m = FileWriteLock{} }
func (m *FileWriteLock) String() string            { return proto.CompactTextString(m) }
func (*FileWriteLock) ProtoMessage()               {}
func (*FileWriteLock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *FileWriteLock) GetGroup() uint64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *FileWriteLock) GetOwner() uint64 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *FileWriteLock) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type DirectoryItem struct {
	Type DirectoryItem_ItemType `protobuf:"varint,1,opt,name=type,enum=client.DirectoryItem_ItemType" json:"type,omitempty"`
	File *FileMeta              `protobuf:"bytes,2,opt,name=file" json:"file,omitempty"`
	Dir  *Directory             `protobuf:"bytes,3,opt,name=dir" json:"dir,omitempty"`
}

func (m *DirectoryItem) Reset()                    { *m = DirectoryItem{} }
func (m *DirectoryItem) String() string            { return proto.CompactTextString(m) }
func (*DirectoryItem) ProtoMessage()               {}
func (*DirectoryItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *DirectoryItem) GetType() DirectoryItem_ItemType {
	if m != nil {
		return m.Type
	}
	return DirectoryItem_FILE
}

func (m *DirectoryItem) GetFile() *FileMeta {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *DirectoryItem) GetDir() *Directory {
	if m != nil {
		return m.Dir
	}
	return nil
}

type ListDirectoryResponse struct {
	Name  string           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Key   []byte           `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Items []*DirectoryItem `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
}

func (m *ListDirectoryResponse) Reset()                    { *m = ListDirectoryResponse{} }
func (m *ListDirectoryResponse) String() string            { return proto.CompactTextString(m) }
func (*ListDirectoryResponse) ProtoMessage()               {}
func (*ListDirectoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ListDirectoryResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListDirectoryResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ListDirectoryResponse) GetItems() []*DirectoryItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type ListDirectoryRequest struct {
	Group uint64 `protobuf:"varint,1,opt,name=group" json:"group,omitempty"`
	Path  string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
}

func (m *ListDirectoryRequest) Reset()                    { *m = ListDirectoryRequest{} }
func (m *ListDirectoryRequest) String() string            { return proto.CompactTextString(m) }
func (*ListDirectoryRequest) ProtoMessage()               {}
func (*ListDirectoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ListDirectoryRequest) GetGroup() uint64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *ListDirectoryRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Nothing struct {
}

func (m *Nothing) Reset()                    { *m = Nothing{} }
func (m *Nothing) String() string            { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()               {}
func (*Nothing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func init() {
	proto.RegisterType((*BlockData)(nil), "client.BlockData")
	proto.RegisterType((*Block)(nil), "client.Block")
	proto.RegisterType((*FileMeta)(nil), "client.FileMeta")
	proto.RegisterType((*Directory)(nil), "client.Directory")
	proto.RegisterType((*Volume)(nil), "client.Volume")
	proto.RegisterType((*HostStash)(nil), "client.HostStash")
	proto.RegisterType((*OpenRequest)(nil), "client.OpenRequest")
	proto.RegisterType((*GetBlockRequest)(nil), "client.GetBlockRequest")
	proto.RegisterType((*AppendToBlockRequest)(nil), "client.AppendToBlockRequest")
	proto.RegisterType((*DeleteBlockRequest)(nil), "client.DeleteBlockRequest")
	proto.RegisterType((*CreateBlockRequest)(nil), "client.CreateBlockRequest")
	proto.RegisterType((*GetFileRequest)(nil), "client.GetFileRequest")
	proto.RegisterType((*GetVolumeRequest)(nil), "client.GetVolumeRequest")
	proto.RegisterType((*GetDirectoryRequest)(nil), "client.GetDirectoryRequest")
	proto.RegisterType((*Node)(nil), "client.Node")
	proto.RegisterType((*BlockStashSuggestion)(nil), "client.BlockStashSuggestion")
	proto.RegisterType((*WriteResult)(nil), "client.WriteResult")
	proto.RegisterType((*NewDirectoryContract)(nil), "client.NewDirectoryContract")
	proto.RegisterType((*AcquireFileWriteLockContract)(nil), "client.AcquireFileWriteLockContract")
	proto.RegisterType((*ReleaseFileWriteLockContract)(nil), "client.ReleaseFileWriteLockContract")
	proto.RegisterType((*TouchFileContract)(nil), "client.TouchFileContract")
	proto.RegisterType((*ConfirmBlockContract)(nil), "client.ConfirmBlockContract")
	proto.RegisterType((*ConfirmBlockCreationContract)(nil), "client.ConfirmBlockCreationContract")
	proto.RegisterType((*FileWriteLock)(nil), "client.FileWriteLock")
	proto.RegisterType((*DirectoryItem)(nil), "client.DirectoryItem")
	proto.RegisterType((*ListDirectoryResponse)(nil), "client.ListDirectoryResponse")
	proto.RegisterType((*ListDirectoryRequest)(nil), "client.ListDirectoryRequest")
	proto.RegisterType((*Nothing)(nil), "client.Nothing")
	proto.RegisterEnum("client.DirectoryItem_ItemType", DirectoryItem_ItemType_name, DirectoryItem_ItemType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PCFS service

type PCFSClient interface {
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*BlockData, error)
	GetFileMeta(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*FileMeta, error)
	GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*Volume, error)
	GetDirectory(ctx context.Context, in *GetDirectoryRequest, opts ...grpc.CallOption) (*Directory, error)
	ListDirectory(ctx context.Context, in *ListDirectoryRequest, opts ...grpc.CallOption) (*ListDirectoryResponse, error)
	AppendToBlock(ctx context.Context, in *AppendToBlockRequest, opts ...grpc.CallOption) (*WriteResult, error)
	CreateBlock(ctx context.Context, in *CreateBlockRequest, opts ...grpc.CallOption) (*WriteResult, error)
	DeleteBlock(ctx context.Context, in *DeleteBlockRequest, opts ...grpc.CallOption) (*WriteResult, error)
	SuggestBlockStash(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*BlockStashSuggestion, error)
}

type pCFSClient struct {
	cc *grpc.ClientConn
}

func NewPCFSClient(cc *grpc.ClientConn) PCFSClient {
	return &pCFSClient{cc}
}

func (c *pCFSClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*BlockData, error) {
	out := new(BlockData)
	err := grpc.Invoke(ctx, "/client.PCFS/GetBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCFSClient) GetFileMeta(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*FileMeta, error) {
	out := new(FileMeta)
	err := grpc.Invoke(ctx, "/client.PCFS/GetFileMeta", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCFSClient) GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*Volume, error) {
	out := new(Volume)
	err := grpc.Invoke(ctx, "/client.PCFS/GetVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCFSClient) GetDirectory(ctx context.Context, in *GetDirectoryRequest, opts ...grpc.CallOption) (*Directory, error) {
	out := new(Directory)
	err := grpc.Invoke(ctx, "/client.PCFS/GetDirectory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCFSClient) ListDirectory(ctx context.Context, in *ListDirectoryRequest, opts ...grpc.CallOption) (*ListDirectoryResponse, error) {
	out := new(ListDirectoryResponse)
	err := grpc.Invoke(ctx, "/client.PCFS/ListDirectory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCFSClient) AppendToBlock(ctx context.Context, in *AppendToBlockRequest, opts ...grpc.CallOption) (*WriteResult, error) {
	out := new(WriteResult)
	err := grpc.Invoke(ctx, "/client.PCFS/AppendToBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCFSClient) CreateBlock(ctx context.Context, in *CreateBlockRequest, opts ...grpc.CallOption) (*WriteResult, error) {
	out := new(WriteResult)
	err := grpc.Invoke(ctx, "/client.PCFS/CreateBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCFSClient) DeleteBlock(ctx context.Context, in *DeleteBlockRequest, opts ...grpc.CallOption) (*WriteResult, error) {
	out := new(WriteResult)
	err := grpc.Invoke(ctx, "/client.PCFS/DeleteBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCFSClient) SuggestBlockStash(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*BlockStashSuggestion, error) {
	out := new(BlockStashSuggestion)
	err := grpc.Invoke(ctx, "/client.PCFS/SuggestBlockStash", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PCFS service

type PCFSServer interface {
	GetBlock(context.Context, *GetBlockRequest) (*BlockData, error)
	GetFileMeta(context.Context, *GetFileRequest) (*FileMeta, error)
	GetVolume(context.Context, *GetVolumeRequest) (*Volume, error)
	GetDirectory(context.Context, *GetDirectoryRequest) (*Directory, error)
	ListDirectory(context.Context, *ListDirectoryRequest) (*ListDirectoryResponse, error)
	AppendToBlock(context.Context, *AppendToBlockRequest) (*WriteResult, error)
	CreateBlock(context.Context, *CreateBlockRequest) (*WriteResult, error)
	DeleteBlock(context.Context, *DeleteBlockRequest) (*WriteResult, error)
	SuggestBlockStash(context.Context, *Nothing) (*BlockStashSuggestion, error)
}

func RegisterPCFSServer(s *grpc.Server, srv PCFSServer) {
	s.RegisterService(&_PCFS_serviceDesc, srv)
}

func _PCFS_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFSServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.PCFS/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFSServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCFS_GetFileMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFSServer).GetFileMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.PCFS/GetFileMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFSServer).GetFileMeta(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCFS_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFSServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.PCFS/GetVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFSServer).GetVolume(ctx, req.(*GetVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCFS_GetDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFSServer).GetDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.PCFS/GetDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFSServer).GetDirectory(ctx, req.(*GetDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCFS_ListDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFSServer).ListDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.PCFS/ListDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFSServer).ListDirectory(ctx, req.(*ListDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCFS_AppendToBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendToBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFSServer).AppendToBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.PCFS/AppendToBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFSServer).AppendToBlock(ctx, req.(*AppendToBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCFS_CreateBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFSServer).CreateBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.PCFS/CreateBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFSServer).CreateBlock(ctx, req.(*CreateBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCFS_DeleteBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFSServer).DeleteBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.PCFS/DeleteBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFSServer).DeleteBlock(ctx, req.(*DeleteBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCFS_SuggestBlockStash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFSServer).SuggestBlockStash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.PCFS/SuggestBlockStash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFSServer).SuggestBlockStash(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

var _PCFS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "client.PCFS",
	HandlerType: (*PCFSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlock",
			Handler:    _PCFS_GetBlock_Handler,
		},
		{
			MethodName: "GetFileMeta",
			Handler:    _PCFS_GetFileMeta_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _PCFS_GetVolume_Handler,
		},
		{
			MethodName: "GetDirectory",
			Handler:    _PCFS_GetDirectory_Handler,
		},
		{
			MethodName: "ListDirectory",
			Handler:    _PCFS_ListDirectory_Handler,
		},
		{
			MethodName: "AppendToBlock",
			Handler:    _PCFS_AppendToBlock_Handler,
		},
		{
			MethodName: "CreateBlock",
			Handler:    _PCFS_CreateBlock_Handler,
		},
		{
			MethodName: "DeleteBlock",
			Handler:    _PCFS_DeleteBlock_Handler,
		},
		{
			MethodName: "SuggestBlockStash",
			Handler:    _PCFS_SuggestBlockStash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}

func init() { proto.RegisterFile("proto/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x5d, 0x6f, 0x1b, 0x45,
	0x17, 0xf6, 0xda, 0xeb, 0xaf, 0x63, 0xbb, 0x4d, 0xa6, 0x6e, 0xeb, 0xfa, 0x75, 0x5e, 0xac, 0x29,
	0xa0, 0x48, 0xa0, 0x50, 0xb9, 0x17, 0x40, 0x05, 0x52, 0x43, 0x4c, 0x42, 0xa4, 0x24, 0xc0, 0x3a,
	0x02, 0x89, 0x1b, 0x6b, 0xbb, 0x7b, 0x92, 0x4c, 0x63, 0xef, 0x6c, 0x76, 0xc6, 0x94, 0x70, 0x89,
	0x90, 0xb8, 0xe1, 0xaf, 0xf0, 0x57, 0xb8, 0xe4, 0xf7, 0xa0, 0x99, 0xd9, 0x4f, 0x3b, 0x49, 0x0d,
	0xdc, 0x58, 0x7b, 0xce, 0xcc, 0x9c, 0xcf, 0xe7, 0x3c, 0x33, 0x86, 0xfb, 0x61, 0xc4, 0x25, 0xff,
	0xc8, 0x0d, 0xd9, 0x8e, 0xfe, 0x22, 0x35, 0x6f, 0xc6, 0x30, 0x90, 0x54, 0x40, 0xf3, 0x8b, 0x19,
	0xf7, 0x2e, 0xc7, 0xae, 0x74, 0x49, 0x17, 0xaa, 0xe7, 0x11, 0x5f, 0x84, 0x3d, 0x6b, 0x68, 0x6d,
	0xdb, 0x8e, 0x11, 0x94, 0x96, 0x05, 0x3e, 0xfe, 0xd4, 0x2b, 0x1b, 0xad, 0x16, 0x08, 0x01, 0x5b,
	0xb0, 0x9f, 0xb1, 0x57, 0x19, 0x5a, 0xdb, 0x1d, 0x47, 0x7f, 0x2b, 0xdd, 0x19, 0x9b, 0x61, 0xcf,
	0x1e, 0x5a, 0xdb, 0x6d, 0x47, 0x7f, 0x2b, 0x9d, 0xef, 0x4a, 0xb7, 0x57, 0x35, 0x3a, 0xf5, 0x4d,
	0xb7, 0xa0, 0xaa, 0x9d, 0x2a, 0xd3, 0x17, 0x5c, 0x48, 0xd1, 0x2b, 0x0f, 0x2b, 0xca, 0xb4, 0x16,
	0xe8, 0x9f, 0x16, 0x34, 0xf6, 0xd9, 0x0c, 0x8f, 0x51, 0xba, 0xea, 0x7c, 0xe0, 0xce, 0x51, 0x87,
	0xd4, 0x74, 0xf4, 0x77, 0xea, 0xdb, 0x04, 0x64, 0x7c, 0x3f, 0x85, 0xce, 0xcc, 0x15, 0x72, 0x3a,
	0xe7, 0x3e, 0x3b, 0x63, 0xe8, 0xeb, 0xc0, 0x6c, 0xa7, 0xad, 0x94, 0xc7, 0xb1, 0x8e, 0x6c, 0x01,
	0x78, 0x11, 0xba, 0x12, 0xfd, 0xa9, 0x2b, 0x75, 0x98, 0xb6, 0xd3, 0x8c, 0x35, 0xbb, 0x52, 0x2d,
	0xbf, 0x52, 0x71, 0x4d, 0xb5, 0xf5, 0x9a, 0xce, 0xac, 0xa9, 0x35, 0x13, 0xe5, 0x62, 0x03, 0x2a,
	0x97, 0x78, 0xdd, 0xab, 0xeb, 0x4c, 0xd4, 0x27, 0x79, 0x0f, 0x6a, 0x7a, 0x59, 0xf4, 0x1a, 0xc3,
	0xca, 0x76, 0x6b, 0xd4, 0xd9, 0x31, 0x65, 0xdd, 0xd1, 0xe9, 0x39, 0xf1, 0x22, 0x3d, 0x80, 0xe6,
	0x98, 0x45, 0xe8, 0x49, 0x1e, 0x5d, 0xdf, 0x98, 0x50, 0x6c, 0xb9, 0x9c, 0x59, 0xee, 0x42, 0x55,
	0x95, 0x4f, 0xf4, 0x2a, 0xc3, 0xca, 0x76, 0xdb, 0x31, 0x02, 0xfd, 0xdd, 0x82, 0xda, 0x77, 0x7c,
	0xb6, 0x30, 0x35, 0x58, 0xc3, 0x0c, 0x85, 0x76, 0x84, 0xe1, 0x8c, 0x79, 0xae, 0x64, 0x3c, 0x10,
	0x71, 0xb7, 0x0a, 0xba, 0xa5, 0xac, 0xed, 0xe5, 0xac, 0x9f, 0x40, 0x23, 0xe2, 0x5c, 0x4e, 0x7d,
	0x16, 0xc5, 0x4d, 0xac, 0x2b, 0x79, 0xcc, 0x22, 0xfa, 0x1a, 0x9a, 0x5f, 0x71, 0x21, 0x27, 0xd2,
	0x15, 0x17, 0xe4, 0x31, 0xd4, 0x55, 0xfb, 0xa6, 0xcc, 0x8f, 0xe1, 0x53, 0x53, 0xe2, 0xa1, 0x4f,
	0xfa, 0xd0, 0xf0, 0xdc, 0xd0, 0xf5, 0x98, 0xbc, 0x8e, 0x3b, 0x96, 0xca, 0x2a, 0x8b, 0x85, 0x48,
	0x9b, 0xa5, 0xbf, 0x55, 0xea, 0xfc, 0x4d, 0x80, 0x51, 0xdc, 0x1f, 0x23, 0xd0, 0xe7, 0xd0, 0xfa,
	0x3a, 0xc4, 0xc0, 0xc1, 0xab, 0x05, 0x0a, 0xb9, 0x5e, 0xfa, 0xf4, 0x5b, 0xb8, 0x7f, 0x80, 0xd2,
	0x34, 0x23, 0x3e, 0xf8, 0x0f, 0x31, 0xae, 0xf1, 0x5c, 0xc9, 0xf0, 0x4c, 0x7f, 0xb1, 0xa0, 0xbb,
	0x1b, 0x86, 0x18, 0xf8, 0xa7, 0xfc, 0x5f, 0x1b, 0x7e, 0x04, 0x35, 0x7e, 0x76, 0x26, 0x50, 0xc6,
	0x0d, 0x89, 0xa5, 0xb5, 0x07, 0xe8, 0x7d, 0x20, 0x63, 0x9c, 0xa1, 0xc4, 0x42, 0x04, 0x71, 0xfe,
	0x56, 0x96, 0x7f, 0x04, 0x64, 0x4f, 0xa3, 0xfb, 0x3f, 0x97, 0x20, 0x1f, 0xd1, 0x00, 0x9a, 0x82,
	0x9d, 0x07, 0xae, 0x5c, 0x44, 0x18, 0x87, 0x95, 0x29, 0xe8, 0x0b, 0xb8, 0x77, 0x80, 0x52, 0xcd,
	0xef, 0xdd, 0xfe, 0x12, 0xcb, 0xe5, 0x5c, 0x71, 0x3f, 0x83, 0x8d, 0x03, 0x94, 0x06, 0xe1, 0x6f,
	0x3d, 0xad, 0xfb, 0x5f, 0xce, 0xfa, 0x4f, 0x3f, 0x87, 0x07, 0x07, 0x28, 0xd3, 0x49, 0xbb, 0xdb,
	0xc0, 0x2a, 0x58, 0x26, 0x60, 0x9f, 0x70, 0x1f, 0x49, 0x0f, 0xea, 0xae, 0xef, 0x47, 0x28, 0x44,
	0x8c, 0xae, 0x44, 0x54, 0x10, 0x0f, 0xb8, 0x8f, 0x0a, 0xe2, 0xa6, 0x48, 0x35, 0x25, 0x1e, 0xfa,
	0xea, 0x48, 0x84, 0x73, 0x97, 0xc5, 0x13, 0x66, 0x3b, 0x89, 0x48, 0x5f, 0x40, 0x57, 0xd7, 0x5e,
	0xcf, 0xc8, 0x64, 0x71, 0x7e, 0x8e, 0x42, 0x4d, 0x1d, 0xa1, 0x50, 0x55, 0x67, 0x95, 0x0b, 0x45,
	0x1c, 0xed, 0x84, 0x38, 0x54, 0x04, 0x8e, 0x59, 0xa2, 0x13, 0x68, 0x7d, 0x1f, 0x31, 0x89, 0x0e,
	0x8a, 0xc5, 0x4c, 0x2a, 0x27, 0x62, 0xe1, 0x79, 0x88, 0x66, 0xc0, 0x1a, 0x4e, 0x22, 0xe6, 0xdd,
	0x97, 0x0b, 0xee, 0x93, 0x2c, 0x2b, 0x59, 0x96, 0x3f, 0x40, 0xf7, 0x04, 0xdf, 0xa4, 0x45, 0xda,
	0xe3, 0x81, 0x8c, 0x5c, 0x4f, 0x73, 0x5f, 0xe8, 0x46, 0x18, 0x98, 0x41, 0x37, 0x18, 0x6a, 0x1a,
	0xcd, 0x98, 0x45, 0xe4, 0x29, 0x54, 0x94, 0x5e, 0x19, 0x6a, 0x8d, 0x36, 0x93, 0x68, 0xb3, 0x5a,
	0xab, 0x55, 0xfa, 0x0c, 0x06, 0xbb, 0xde, 0xd5, 0x82, 0x45, 0xa8, 0xda, 0xaf, 0x63, 0x3f, 0xe2,
	0xde, 0x65, 0xea, 0x63, 0x15, 0xa0, 0xcf, 0x60, 0xe0, 0xe0, 0x0c, 0x5d, 0xb1, 0xf6, 0x89, 0x08,
	0x36, 0x4f, 0xf9, 0xc2, 0xbb, 0x50, 0xfb, 0xd3, 0x6d, 0xef, 0x40, 0xcb, 0x44, 0x34, 0x95, 0x2c,
	0x26, 0x05, 0xdb, 0x01, 0xa3, 0x3a, 0x65, 0x39, 0xb6, 0x2c, 0x17, 0xe9, 0x22, 0x49, 0xa9, 0xad,
	0xe3, 0x57, 0x63, 0xf9, 0xa3, 0xc6, 0x5e, 0x0c, 0xf7, 0x58, 0xa2, 0xbf, 0x59, 0xd0, 0xdd, 0xe3,
	0xc1, 0x19, 0x8b, 0xe6, 0xba, 0x99, 0xa9, 0xdf, 0x1c, 0x20, 0xac, 0x02, 0x20, 0xd6, 0xe6, 0x13,
	0xf2, 0x21, 0x54, 0x22, 0xbc, 0xd2, 0x0e, 0x5b, 0xa3, 0x7e, 0x52, 0xd8, 0xd5, 0xa9, 0x75, 0xd4,
	0x36, 0xfa, 0xab, 0x05, 0x83, 0x42, 0x24, 0x6a, 0x1f, 0xe3, 0x41, 0x1a, 0x51, 0xea, 0xd8, 0xca,
	0x3b, 0x5e, 0xaa, 0x4f, 0x79, 0xa5, 0x3e, 0x4f, 0xa0, 0x11, 0x27, 0x62, 0x6e, 0x1c, 0xdb, 0xa9,
	0x9b, 0x4c, 0xc4, 0x4d, 0x0c, 0x40, 0x8f, 0xa1, 0x53, 0xe8, 0xd7, 0xed, 0x94, 0x62, 0x98, 0xbc,
	0x9c, 0x63, 0xf2, 0xa4, 0xa7, 0x76, 0xd6, 0xd3, 0x3f, 0x2c, 0xe8, 0xa4, 0x50, 0x3a, 0x94, 0x38,
	0x27, 0x23, 0xb0, 0xe5, 0x75, 0x68, 0x3a, 0x79, 0x6f, 0xf4, 0xff, 0x15, 0xbc, 0xa9, 0x4d, 0x3b,
	0xea, 0xe7, 0xf4, 0x3a, 0x44, 0x47, 0xef, 0x25, 0xef, 0xe6, 0x08, 0xa5, 0x35, 0xda, 0x48, 0xce,
	0x24, 0x2f, 0x89, 0xb8, 0xde, 0x6b, 0x01, 0x79, 0x0b, 0x1a, 0x89, 0x71, 0xd2, 0x00, 0x7b, 0xff,
	0xf0, 0xe8, 0xcb, 0x8d, 0x12, 0xa9, 0x43, 0x65, 0x7c, 0xe8, 0x6c, 0x58, 0xf4, 0x35, 0x3c, 0x3c,
	0x62, 0x22, 0xcf, 0x34, 0x22, 0xe4, 0x81, 0x58, 0xf7, 0x52, 0xfe, 0x00, 0xaa, 0x4c, 0xe2, 0xdc,
	0x54, 0xba, 0x35, 0x7a, 0x78, 0x63, 0x76, 0x8e, 0xd9, 0x43, 0x5f, 0x42, 0x77, 0xc9, 0xd7, 0x5b,
	0x68, 0x31, 0x74, 0xe5, 0x45, 0x82, 0x73, 0xf5, 0x4d, 0x9b, 0x50, 0x3f, 0xe1, 0xf2, 0x82, 0x05,
	0xe7, 0xa3, 0xbf, 0x6c, 0xb0, 0xbf, 0xd9, 0xdb, 0x9f, 0x90, 0x4f, 0xa0, 0x91, 0x5c, 0x8c, 0xe4,
	0x71, 0xe2, 0x7f, 0xe9, 0xaa, 0xec, 0x6f, 0x16, 0x5e, 0x33, 0xea, 0x85, 0x48, 0x4b, 0xe4, 0x53,
	0x68, 0xc5, 0xf4, 0xae, 0x9f, 0x67, 0x8f, 0x72, 0x87, 0x73, 0x9c, 0xdf, 0x5f, 0x29, 0x3f, 0x2d,
	0x91, 0x8f, 0xa1, 0x99, 0xb2, 0x3b, 0xe9, 0xe5, 0x0e, 0x16, 0x08, 0xbf, 0x7f, 0x2f, 0x59, 0x31,
	0x6a, 0x5a, 0x22, 0x2f, 0xa1, 0x9d, 0x27, 0x76, 0xf2, 0xbf, 0xdc, 0xd9, 0xe5, 0xc2, 0xf4, 0x57,
	0x7b, 0x4a, 0x4b, 0xe4, 0x04, 0x3a, 0x85, 0x2a, 0x92, 0x41, 0xb2, 0xeb, 0xa6, 0xe2, 0xf6, 0xb7,
	0x6e, 0x59, 0x35, 0x6d, 0xa6, 0x25, 0x32, 0x86, 0x4e, 0xe1, 0x11, 0x90, 0xd9, 0xbb, 0xe9, 0x6d,
	0xd0, 0x7f, 0x90, 0xac, 0xe6, 0xf8, 0x5c, 0xe7, 0xd5, 0xca, 0x0d, 0x3a, 0xb9, 0x63, 0xfa, 0xef,
	0xb0, 0x90, 0x7b, 0x08, 0x64, 0x16, 0x56, 0x5f, 0x07, 0xb7, 0x59, 0x18, 0xc3, 0x66, 0x7c, 0x2d,
	0x65, 0xf7, 0x14, 0xb9, 0x9f, 0x5d, 0x47, 0x1a, 0x38, 0xfd, 0x41, 0x01, 0x0a, 0x4b, 0x97, 0x19,
	0x2d, 0xbd, 0xaa, 0xe9, 0x7f, 0x15, 0xcf, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xad, 0x78, 0x69,
	0xf3, 0x68, 0x0c, 0x00, 0x00,
}
