// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api.proto

/*
Package client is a generated protocol buffer package.

It is generated from these files:
	proto/api.proto

It has these top-level messages:
	Block
	FileMeta
	Directory
	Volume
	HostStash
	OpenRequest
	GetBlockRequest
	GetBlockResponse
	AppendToBlockRequest
	DeleteBlockRequest
	WriteResult
	Nothing
*/
package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Block struct {
	Hash  []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Key   []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Hosts []uint64 `protobuf:"varint,1,rep,packed,name=hosts" json:"hosts,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Block) GetHosts() []uint64 {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type FileMeta struct {
	Name          string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Size          uint64   `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Last_Modified uint64   `protobuf:"varint,3,opt,name=last_Modified,json=lastModified" json:"last_Modified,omitempty"`
	CreatedAt     uint64   `protobuf:"varint,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	LockTime      uint64   `protobuf:"varint,5,opt,name=lock_time,json=lockTime" json:"lock_time,omitempty"`
	Key           []byte   `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Blocks        []*Block `protobuf:"bytes,7,rep,name=blocks" json:"blocks,omitempty"`
}

func (m *FileMeta) Reset()                    { *m = FileMeta{} }
func (m *FileMeta) String() string            { return proto.CompactTextString(m) }
func (*FileMeta) ProtoMessage()               {}
func (*FileMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FileMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileMeta) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileMeta) GetLast_Modified() uint64 {
	if m != nil {
		return m.Last_Modified
	}
	return 0
}

func (m *FileMeta) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *FileMeta) GetLockTime() uint64 {
	if m != nil {
		return m.LockTime
	}
	return 0
}

func (m *FileMeta) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *FileMeta) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type Directory struct {
	Name  string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Key   []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Files [][]byte `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
}

func (m *Directory) Reset()                    { *m = Directory{} }
func (m *Directory) String() string            { return proto.CompactTextString(m) }
func (*Directory) ProtoMessage()               {}
func (*Directory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Directory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Directory) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Directory) GetFiles() [][]byte {
	if m != nil {
		return m.Files
	}
	return nil
}

type Volume struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Key          []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Replications uint32 `protobuf:"varint,3,opt,name=replications" json:"replications,omitempty"`
	RootDir      []byte `protobuf:"bytes,4,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
}

func (m *Volume) Reset()                    { *m = Volume{} }
func (m *Volume) String() string            { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()               {}
func (*Volume) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Volume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Volume) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Volume) GetReplications() uint32 {
	if m != nil {
		return m.Replications
	}
	return 0
}

func (m *Volume) GetRootDir() []byte {
	if m != nil {
		return m.RootDir
	}
	return nil
}

type HostStash struct {
	HostId   uint64 `protobuf:"varint,1,opt,name=host_id,json=hostId" json:"host_id,omitempty"`
	Capacity uint64 `protobuf:"varint,2,opt,name=capacity" json:"capacity,omitempty"`
	Used     uint64 `protobuf:"varint,3,opt,name=used" json:"used,omitempty"`
	Owner    uint64 `protobuf:"varint,4,opt,name=owner" json:"owner,omitempty"`
}

func (m *HostStash) Reset()                    { *m = HostStash{} }
func (m *HostStash) String() string            { return proto.CompactTextString(m) }
func (*HostStash) ProtoMessage()               {}
func (*HostStash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HostStash) GetHostId() uint64 {
	if m != nil {
		return m.HostId
	}
	return 0
}

func (m *HostStash) GetCapacity() uint64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *HostStash) GetUsed() uint64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *HostStash) GetOwner() uint64 {
	if m != nil {
		return m.Owner
	}
	return 0
}

type OpenRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Key  []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *OpenRequest) Reset()                    { *m = OpenRequest{} }
func (m *OpenRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenRequest) ProtoMessage()               {}
func (*OpenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *OpenRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OpenRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetBlockRequest struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *GetBlockRequest) Reset()                    { *m = GetBlockRequest{} }
func (m *GetBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlockRequest) ProtoMessage()               {}
func (*GetBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetBlockRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetBlockResponse struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *GetBlockResponse) Reset()                    { *m = GetBlockResponse{} }
func (m *GetBlockResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBlockResponse) ProtoMessage()               {}
func (*GetBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetBlockResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AppendToBlockRequest struct {
	Key  []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *AppendToBlockRequest) Reset()                    { *m = AppendToBlockRequest{} }
func (m *AppendToBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*AppendToBlockRequest) ProtoMessage()               {}
func (*AppendToBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AppendToBlockRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *AppendToBlockRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteBlockRequest struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *DeleteBlockRequest) Reset()                    { *m = DeleteBlockRequest{} }
func (m *DeleteBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteBlockRequest) ProtoMessage()               {}
func (*DeleteBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteBlockRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type WriteResult struct {
	Succeed bool   `protobuf:"varint,1,opt,name=succeed" json:"succeed,omitempty"`
	Remains uint64 `protobuf:"varint,2,opt,name=remains" json:"remains,omitempty"`
	Key     []byte `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *WriteResult) Reset()                    { *m = WriteResult{} }
func (m *WriteResult) String() string            { return proto.CompactTextString(m) }
func (*WriteResult) ProtoMessage()               {}
func (*WriteResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *WriteResult) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

func (m *WriteResult) GetRemains() uint64 {
	if m != nil {
		return m.Remains
	}
	return 0
}

func (m *WriteResult) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type Nothing struct {
}

func (m *Nothing) Reset()                    { *m = Nothing{} }
func (m *Nothing) String() string            { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()               {}
func (*Nothing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func init() {
	proto.RegisterType((*Block)(nil), "client.Block")
	proto.RegisterType((*FileMeta)(nil), "client.FileMeta")
	proto.RegisterType((*Directory)(nil), "client.Directory")
	proto.RegisterType((*Volume)(nil), "client.Volume")
	proto.RegisterType((*HostStash)(nil), "client.HostStash")
	proto.RegisterType((*OpenRequest)(nil), "client.OpenRequest")
	proto.RegisterType((*GetBlockRequest)(nil), "client.GetBlockRequest")
	proto.RegisterType((*GetBlockResponse)(nil), "client.GetBlockResponse")
	proto.RegisterType((*AppendToBlockRequest)(nil), "client.AppendToBlockRequest")
	proto.RegisterType((*DeleteBlockRequest)(nil), "client.DeleteBlockRequest")
	proto.RegisterType((*WriteResult)(nil), "client.WriteResult")
	proto.RegisterType((*Nothing)(nil), "client.Nothing")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PCFS service

type PCFSClient interface {
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	AppendToBlock(ctx context.Context, in *AppendToBlockRequest, opts ...grpc.CallOption) (*WriteResult, error)
	DeleteBlock(ctx context.Context, in *DeleteBlockRequest, opts ...grpc.CallOption) (*WriteResult, error)
}

type pCFSClient struct {
	cc *grpc.ClientConn
}

func NewPCFSClient(cc *grpc.ClientConn) PCFSClient {
	return &pCFSClient{cc}
}

func (c *pCFSClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	out := new(GetBlockResponse)
	err := grpc.Invoke(ctx, "/client.PCFS/GetBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCFSClient) AppendToBlock(ctx context.Context, in *AppendToBlockRequest, opts ...grpc.CallOption) (*WriteResult, error) {
	out := new(WriteResult)
	err := grpc.Invoke(ctx, "/client.PCFS/AppendToBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCFSClient) DeleteBlock(ctx context.Context, in *DeleteBlockRequest, opts ...grpc.CallOption) (*WriteResult, error) {
	out := new(WriteResult)
	err := grpc.Invoke(ctx, "/client.PCFS/DeleteBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PCFS service

type PCFSServer interface {
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	AppendToBlock(context.Context, *AppendToBlockRequest) (*WriteResult, error)
	DeleteBlock(context.Context, *DeleteBlockRequest) (*WriteResult, error)
}

func RegisterPCFSServer(s *grpc.Server, srv PCFSServer) {
	s.RegisterService(&_PCFS_serviceDesc, srv)
}

func _PCFS_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFSServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.PCFS/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFSServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCFS_AppendToBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendToBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFSServer).AppendToBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.PCFS/AppendToBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFSServer).AppendToBlock(ctx, req.(*AppendToBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCFS_DeleteBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFSServer).DeleteBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.PCFS/DeleteBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFSServer).DeleteBlock(ctx, req.(*DeleteBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PCFS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "client.PCFS",
	HandlerType: (*PCFSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlock",
			Handler:    _PCFS_GetBlock_Handler,
		},
		{
			MethodName: "AppendToBlock",
			Handler:    _PCFS_AppendToBlock_Handler,
		},
		{
			MethodName: "DeleteBlock",
			Handler:    _PCFS_DeleteBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}

func init() { proto.RegisterFile("proto/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x97, 0x25, 0x4b, 0x93, 0x6b, 0xab, 0x4d, 0x66, 0xd2, 0x42, 0x01, 0xa9, 0xf2, 0xc4,
	0xd4, 0xa7, 0x21, 0x6d, 0xaf, 0x48, 0x30, 0x56, 0x6d, 0xf0, 0x30, 0x40, 0xee, 0x04, 0x8f, 0x95,
	0x97, 0xdc, 0xa8, 0x59, 0x1a, 0x07, 0xdb, 0x15, 0x2a, 0x7f, 0x23, 0x12, 0xff, 0x12, 0xb2, 0x93,
	0xf4, 0x07, 0x1d, 0xb0, 0xb7, 0xfb, 0xde, 0x7d, 0x7d, 0xbe, 0xfb, 0xb8, 0x0d, 0xec, 0x96, 0x4a,
	0x1a, 0xf9, 0x82, 0x97, 0xe2, 0xd8, 0x45, 0x24, 0x4c, 0x73, 0x81, 0x85, 0xa1, 0xe7, 0xb0, 0xf3,
	0x26, 0x97, 0xe9, 0x1d, 0x21, 0x10, 0x4c, 0xb8, 0x9e, 0x24, 0xdb, 0x7d, 0x6f, 0xd0, 0x61, 0x2e,
	0x26, 0x7b, 0xe0, 0xdf, 0xe1, 0x3c, 0xf1, 0x5d, 0xca, 0x86, 0x64, 0x1f, 0x76, 0x26, 0x52, 0x1b,
	0x9d, 0x78, 0x7d, 0x7f, 0x10, 0xb0, 0x4a, 0xd0, 0x9f, 0x1e, 0x44, 0x17, 0x22, 0xc7, 0x2b, 0x34,
	0xdc, 0x36, 0x2a, 0xf8, 0x14, 0x13, 0xaf, 0xef, 0x0d, 0x62, 0xe6, 0x62, 0x9b, 0xd3, 0xe2, 0x07,
	0xba, 0xe6, 0x01, 0x73, 0x31, 0x39, 0x84, 0x6e, 0xce, 0xb5, 0x19, 0x5f, 0xc9, 0x4c, 0xdc, 0x0a,
	0xcc, 0xdc, 0x35, 0x01, 0xeb, 0xd8, 0x64, 0x93, 0x23, 0xcf, 0x00, 0x52, 0x85, 0xdc, 0x60, 0x36,
	0xe6, 0x26, 0x09, 0x9c, 0x23, 0xae, 0x33, 0x67, 0x86, 0x3c, 0x81, 0xd8, 0x0e, 0x3f, 0x36, 0x62,
	0x8a, 0xc9, 0x8e, 0xab, 0x46, 0x36, 0x71, 0x2d, 0xa6, 0xd8, 0x4c, 0x1f, 0x2e, 0xa7, 0x7f, 0x0e,
	0xe1, 0x8d, 0x2d, 0xeb, 0xa4, 0xd5, 0xf7, 0x07, 0xed, 0x93, 0xee, 0x71, 0x45, 0xe1, 0xd8, 0x21,
	0x60, 0x75, 0x91, 0x5e, 0x42, 0x3c, 0x14, 0x0a, 0x53, 0x23, 0xd5, 0xfc, 0xde, 0x75, 0xea, 0xce,
	0xdb, 0x6b, 0x5c, 0x6e, 0x45, 0x8e, 0x3a, 0xf1, 0xfb, 0xfe, 0xa0, 0xc3, 0x2a, 0x41, 0xa7, 0x10,
	0x7e, 0x92, 0xf9, 0xac, 0x02, 0xf0, 0x80, 0x2e, 0x14, 0x3a, 0x0a, 0xcb, 0x5c, 0xa4, 0xdc, 0x08,
	0x59, 0x68, 0x47, 0xa4, 0xcb, 0xd6, 0x72, 0xe4, 0x31, 0x44, 0x4a, 0x4a, 0x33, 0xce, 0x84, 0x72,
	0x3c, 0x3a, 0xac, 0x65, 0xf5, 0x50, 0x28, 0xfa, 0x15, 0xe2, 0xb7, 0x52, 0x9b, 0x91, 0xb1, 0x6f,
	0x77, 0x00, 0x2d, 0xfb, 0x38, 0x63, 0x91, 0xb9, 0x4b, 0x03, 0x16, 0x5a, 0xf9, 0x2e, 0x23, 0x3d,
	0x88, 0x52, 0x5e, 0xf2, 0x54, 0x98, 0x79, 0xfd, 0x1e, 0x0b, 0x6d, 0xc7, 0x9c, 0xe9, 0xc5, 0x53,
	0xb8, 0xd8, 0xae, 0x26, 0xbf, 0x17, 0xa8, 0x6a, 0xfa, 0x95, 0xa0, 0xa7, 0xd0, 0xfe, 0x50, 0x62,
	0xc1, 0xf0, 0xdb, 0x0c, 0xb5, 0x79, 0xd8, 0x7e, 0xf4, 0x10, 0x76, 0x2f, 0xd1, 0x54, 0xb0, 0xeb,
	0x83, 0xb5, 0xc9, 0x5b, 0x9a, 0x8e, 0x60, 0x6f, 0x69, 0xd2, 0xa5, 0x2c, 0xb4, 0xc3, 0x97, 0x71,
	0xc3, 0x6b, 0x9b, 0x8b, 0xe9, 0x4b, 0xd8, 0x3f, 0x2b, 0x4b, 0x2c, 0xb2, 0x6b, 0xf9, 0xef, 0x8e,
	0x8b, 0xd3, 0xdb, 0x2b, 0xa7, 0x8f, 0x80, 0x0c, 0x31, 0x47, 0x83, 0xff, 0x99, 0x66, 0x04, 0xed,
	0xcf, 0x4a, 0x18, 0x64, 0xa8, 0x67, 0xb9, 0x21, 0x09, 0xb4, 0xf4, 0x2c, 0x4d, 0x11, 0x2b, 0xaa,
	0x11, 0x6b, 0xa4, 0xad, 0x28, 0x9c, 0x72, 0x51, 0xe8, 0x9a, 0x6a, 0x23, 0x37, 0xff, 0x45, 0x34,
	0x86, 0xd6, 0x7b, 0x69, 0x26, 0xa2, 0xf8, 0x72, 0xf2, 0xcb, 0x83, 0xe0, 0xe3, 0xf9, 0xc5, 0x88,
	0xbc, 0x82, 0xa8, 0x59, 0x9b, 0x1c, 0x34, 0xbf, 0xcb, 0x3f, 0x68, 0xf5, 0x92, 0xcd, 0x42, 0x45,
	0x88, 0x6e, 0x91, 0x21, 0x74, 0xd7, 0x78, 0x90, 0xa7, 0x8d, 0xf9, 0x3e, 0x4c, 0xbd, 0x47, 0x4d,
	0x75, 0x65, 0x3d, 0xba, 0x45, 0x5e, 0x43, 0x7b, 0x85, 0x0b, 0xe9, 0x35, 0xae, 0x4d, 0x58, 0x7f,
	0xe9, 0x70, 0x13, 0xba, 0x0f, 0xcc, 0xe9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x63, 0x2b, 0x0d,
	0x76, 0x73, 0x04, 0x00, 0x00,
}
